### PR TITLE
Update pt-kill patch to dynamically adjust dynamic idle/busy time adjustments on a per-user basis.

### PR DESCRIPTION
**Pull request by pseudomorph**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @pseudomorph, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by geoffreyanderson** [comment]
👍

**Comment by pseudomorph** [comment]
CLA signed.

**Comment by boxcla** [comment]
Verified that @pseudomorph has just signed the CLA. Thanks, and we look forward to your contribution.

**Pull request merged**
